"""baseline schema

Revision ID: 855f02a5fd92
Revises: 
Create Date: 2026-03-23 21:13:33.815871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855f02a5fd92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novel',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('total_chapters', sa.Integer(), nullable=True),
    sa.Column('cover_image_url', sa.String(length=512), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('search_cache_entry',
    sa.Column('novel_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('remote_cover_url', sa.String(length=1024), nullable=True),
    sa.Column('local_cover_path', sa.String(length=1024), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('bookshelf_count', sa.BigInteger(), nullable=True),
    sa.Column('heat_score', sa.Float(), nullable=True),
    sa.Column('search_hits', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('novel_id')
    )
    op.create_table('search_query_cache_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=255), nullable=False),
    sa.Column('result_ids_json', sa.Text(), nullable=False),
    sa.Column('next_offset', sa.Integer(), nullable=True),
    sa.Column('has_more', sa.Boolean(), nullable=False),
    sa.Column('hits', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_query_cache_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_query_cache_entry_query'), ['query'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('chapter',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('novel_id', sa.BigInteger(), nullable=False),
    sa.Column('chapter_index', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('download_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.BigInteger(), nullable=False),
    sa.Column('celery_task_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'DOWNLOADING', 'PROCESSING', 'COMPLETED', 'FAILED', 'TERMINATED', name='taskstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novel.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('celery_task_id')
    )
    with op.batch_alter_table('download_task', schema=None) as batch_op:
        batch_op.create_index('ix_downloadtask_user_status', ['user_id', 'status'], unique=False)

    op.create_table('word_stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.BigInteger(), nullable=False),
    sa.Column('word', sa.String(length=64), nullable=False),
    sa.Column('freq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['novel_id'], ['novel.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('word_stat', schema=None) as batch_op:
        batch_op.create_index('ix_wordstat_novel_word', ['novel_id', 'word'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_stat', schema=None) as batch_op:
        batch_op.drop_index('ix_wordstat_novel_word')

    op.drop_table('word_stat')
    with op.batch_alter_table('download_task', schema=None) as batch_op:
        batch_op.drop_index('ix_downloadtask_user_status')

    op.drop_table('download_task')
    op.drop_table('chapter')
    op.drop_table('user')
    with op.batch_alter_table('search_query_cache_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_query_cache_entry_query'))

    op.drop_table('search_query_cache_entry')
    op.drop_table('search_cache_entry')
    op.drop_table('novel')
    # ### end Alembic commands ###
